#
# This is a docker-compose file to build and start all Lakeside Mutual
# applications in a single command.
#
# To run the applications:
#   docker-compose up
#
# To shut down the applications, simply terminate the previous command.
#

version: '3.7'

services:
  spring-boot-admin:
    build: 
      context: ./spring-boot-admin
    volumes: 
      - ./spring-boot-admin/src:/usr/src/app
    ports:
      - "9000:9000"

  customer-core:
    build: 
      context: ./customer-core
    volumes: 
      - ./customer-core/src:/usr/src/app
    environment:
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8110:8110"

  customer-management-backend:
    build: 
      context: ./customer-management-backend
    depends_on:
      - customer-core
    volumes: 
      - ./customer-management-backend/src:/usr/src/app
    environment:
      - "CUSTOMERCORE_BASEURL=http://customer-core:8110"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8100:8100"

  customer-management-frontend:
    build: 
      context: ./customer-management-frontend
    volumes: 
      - ./customer-management-frontend/src:/usr/src/app
    depends_on:
      - customer-management-backend
    ports:
      - "3020:80"

  policy-management-backend:
    build: 
      context: ./policy-management-backend
    volumes: 
      - ./policy-management-backend/src:/usr/src/app
    depends_on:
      - customer-core
    environment:
      - "CUSTOMERCORE_BASEURL=http://customer-core:8110"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8090:8090"
      - "61613:61613"
      - "61616:61616"

  policy-management-frontend:
    build: ./policy-management-frontend
    volumes: 
      - ./policy-management-frontend/src:/usr/src/app
    depends_on:
      - policy-management-backend
    ports:
      - "3010:80"

  customer-self-service-backend:
    build: 
      context: ./customer-self-service-backend
    volumes: 
      - ./customer-self-service-backend/src:/usr/src/app
    depends_on:
      - customer-core
      - policy-management-backend
    environment:
      - "CUSTOMERCORE_BASEURL=http://customer-core:8110"
      - "POLICYMANAGEMENT_TCPBROKERBINDADDRESS=tcp://policy-management-backend:61616"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8080:8080"

  customer-self-service-frontend:
    build: 
      context: ./customer-self-service-frontend
    volumes: 
      - ./customer-self-service-frontend/src:/usr/src/app
    depends_on:
      - customer-self-service-backend
      - customer-management-backend
      - policy-management-backend
    ports:
      - "3000:80"

  risk-management-server:
    build: 
      context: ./risk-management-server
    volumes: 
      - ./risk-management-server/src:/usr/src/app
    depends_on:
      - policy-management-backend
    environment:
      - "ACTIVEMQ_HOST=policy-management-backend"
      - "ACTIVEMQ_PORT=61613"
    ports:
      - "50051:50051"