// flow-typed signature: 3df647814ac5420c309158d5ebeae8df
// flow-typed version: <<STUB>>/@brigad/redux-rest-easy_v^3.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@brigad/redux-rest-easy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@brigad/redux-rest-easy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@brigad/redux-rest-easy/dist/redux-rest-easy.cjs' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/dist/redux-rest-easy.es' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/dist/redux-rest-easy.umd' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/dist/redux-rest-easy.umd.min' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/connect' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/createResource' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/getPersistableState' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/index' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/initializeNetworkHelpers' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/action-creator/generateThunk' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/action-creator/preflight/isCacheExpired' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/action-creator/preflight/isSmartCacheAvailable' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/action-creator/preflight/shouldPerform' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/action-creator/thunk/generateActionCreator' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions/generateActionCreatorAction' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions/generateActionCreatorActionTypes' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions/generateGlobalAction' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions/generateGlobalActionTypes' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateResourceActions' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateResourceActions/generateResourceAction' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateResourceActions/generateResourceActionTypes' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateThunkActions' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateThunkActions/generateThunkAction' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/actions/generateThunkActions/generateThunkActionTypes' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/config/checkActionsConfig' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/config/checkResourceConfig' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/network/getDefaultNetworkHelpers' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/network/networkHelpers' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/persistence/getPrunedForPersistenceState' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/reducer/generateReducer' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/reducer/generateReducer/getReducerCases' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/selectors/generateActionSelectors' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/selectors/generateResourceSelectors' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/formatURL' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/generateActionType' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/getActionNameFromNormalizedURL' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/getIdSplitIndexFromURL' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/getInfosFromActionType' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/getNormalizedURLFromOwnProps' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/getReReselectOptions' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/getResourceIdFromNormalizedURL' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/getResourceIdsByResourceNameFromNormalizedPayload' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/getState' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/hasCacheExpired' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/hash' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/isPlainObject' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/mergeResources' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/normalizeURL' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/resolversHashes' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/safeCall' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/safeIds' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/internals/utils/stringifyQueryParameters' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/reducer' {
  declare module.exports: any;
}

declare module '@brigad/redux-rest-easy/src/reset' {
  declare module.exports: any;
}

// Filename aliases
declare module '@brigad/redux-rest-easy/dist/redux-rest-easy.cjs.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/dist/redux-rest-easy.cjs'>;
}
declare module '@brigad/redux-rest-easy/dist/redux-rest-easy.es.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/dist/redux-rest-easy.es'>;
}
declare module '@brigad/redux-rest-easy/dist/redux-rest-easy.umd.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/dist/redux-rest-easy.umd'>;
}
declare module '@brigad/redux-rest-easy/dist/redux-rest-easy.umd.min.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/dist/redux-rest-easy.umd.min'>;
}
declare module '@brigad/redux-rest-easy/src/connect.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/connect'>;
}
declare module '@brigad/redux-rest-easy/src/createResource.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/createResource'>;
}
declare module '@brigad/redux-rest-easy/src/getPersistableState.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/getPersistableState'>;
}
declare module '@brigad/redux-rest-easy/src/index.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/index'>;
}
declare module '@brigad/redux-rest-easy/src/initializeNetworkHelpers.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/initializeNetworkHelpers'>;
}
declare module '@brigad/redux-rest-easy/src/internals/action-creator/generateThunk.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/action-creator/generateThunk'>;
}
declare module '@brigad/redux-rest-easy/src/internals/action-creator/preflight/isCacheExpired.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/action-creator/preflight/isCacheExpired'>;
}
declare module '@brigad/redux-rest-easy/src/internals/action-creator/preflight/isSmartCacheAvailable.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/action-creator/preflight/isSmartCacheAvailable'>;
}
declare module '@brigad/redux-rest-easy/src/internals/action-creator/preflight/shouldPerform.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/action-creator/preflight/shouldPerform'>;
}
declare module '@brigad/redux-rest-easy/src/internals/action-creator/thunk/generateActionCreator.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/action-creator/thunk/generateActionCreator'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions/generateActionCreatorAction.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions/generateActionCreatorAction'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions/generateActionCreatorActionTypes.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateActionCreatorActions/generateActionCreatorActionTypes'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions/generateGlobalAction.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions/generateGlobalAction'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions/generateGlobalActionTypes.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateGlobalActions/generateGlobalActionTypes'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateResourceActions.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateResourceActions'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateResourceActions/generateResourceAction.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateResourceActions/generateResourceAction'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateResourceActions/generateResourceActionTypes.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateResourceActions/generateResourceActionTypes'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateThunkActions.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateThunkActions'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateThunkActions/generateThunkAction.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateThunkActions/generateThunkAction'>;
}
declare module '@brigad/redux-rest-easy/src/internals/actions/generateThunkActions/generateThunkActionTypes.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/actions/generateThunkActions/generateThunkActionTypes'>;
}
declare module '@brigad/redux-rest-easy/src/internals/config/checkActionsConfig.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/config/checkActionsConfig'>;
}
declare module '@brigad/redux-rest-easy/src/internals/config/checkResourceConfig.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/config/checkResourceConfig'>;
}
declare module '@brigad/redux-rest-easy/src/internals/network/getDefaultNetworkHelpers.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/network/getDefaultNetworkHelpers'>;
}
declare module '@brigad/redux-rest-easy/src/internals/network/networkHelpers.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/network/networkHelpers'>;
}
declare module '@brigad/redux-rest-easy/src/internals/persistence/getPrunedForPersistenceState.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/persistence/getPrunedForPersistenceState'>;
}
declare module '@brigad/redux-rest-easy/src/internals/reducer/generateReducer.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/reducer/generateReducer'>;
}
declare module '@brigad/redux-rest-easy/src/internals/reducer/generateReducer/getReducerCases.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/reducer/generateReducer/getReducerCases'>;
}
declare module '@brigad/redux-rest-easy/src/internals/selectors/generateActionSelectors.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/selectors/generateActionSelectors'>;
}
declare module '@brigad/redux-rest-easy/src/internals/selectors/generateResourceSelectors.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/selectors/generateResourceSelectors'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/formatURL.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/formatURL'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/generateActionType.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/generateActionType'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/getActionNameFromNormalizedURL.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/getActionNameFromNormalizedURL'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/getIdSplitIndexFromURL.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/getIdSplitIndexFromURL'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/getInfosFromActionType.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/getInfosFromActionType'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/getNormalizedURLFromOwnProps.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/getNormalizedURLFromOwnProps'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/getReReselectOptions.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/getReReselectOptions'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/getResourceIdFromNormalizedURL.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/getResourceIdFromNormalizedURL'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/getResourceIdsByResourceNameFromNormalizedPayload.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/getResourceIdsByResourceNameFromNormalizedPayload'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/getState.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/getState'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/hasCacheExpired.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/hasCacheExpired'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/hash.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/hash'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/isPlainObject.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/isPlainObject'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/mergeResources.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/mergeResources'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/normalizeURL.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/normalizeURL'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/resolversHashes.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/resolversHashes'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/safeCall.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/safeCall'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/safeIds.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/safeIds'>;
}
declare module '@brigad/redux-rest-easy/src/internals/utils/stringifyQueryParameters.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/internals/utils/stringifyQueryParameters'>;
}
declare module '@brigad/redux-rest-easy/src/reducer.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/reducer'>;
}
declare module '@brigad/redux-rest-easy/src/reset.js' {
  declare module.exports: $Exports<'@brigad/redux-rest-easy/src/reset'>;
}
