// flow-typed signature: 89b3af97c3d5b60f1e7a22ce11e4cef6
// flow-typed version: <<STUB>>/react-stomp_v^3.3.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stomp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stomp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-stomp/dist/client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-stomp/dist/client.js' {
  declare module.exports: $Exports<'react-stomp/dist/client'>;
}
