package com.lakesidemutual.customerselfservice.interfaces.configuration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Collections;
import java.util.function.Predicate;

/**
 * The SwaggerConfiguration class configures the HTTP resource API documentation
 * that is generated by Springfox.
 */
@Configuration
public class SwaggerConfiguration {

	@Bean
	public OpenAPI customerSelfServiceApi() {
		return new OpenAPI()
				.info(new Info().title("Customer Self-Service API")
						.description("This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.")
						.version("v1.0.0")
						.license(new License().name("Apache 2.0")));
	}
}
